src/Entity/Abonne.php
<?php

namespace App\Entity;

use App\Repository\AbonneRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=AbonneRepository::class)
 * @UniqueEntity(fields={"pseudo"}, message="There is already an account with this pseudo")
 */
class Abonne implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $pseudo;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $prenom;

    /**
     * @ORM\OneToMany(targetEntity=Emprunt::class, mappedBy="abonne")
     */
    private $emprunts;

    public function __construct()
    {
        $this->emprunts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * @return Collection|Emprunt[]
     */
    public function getEmprunts(): Collection
    {
        return $this->emprunts;
    }

    public function addEmprunt(Emprunt $emprunt): self
    {
        if (!$this->emprunts->contains($emprunt)) {
            $this->emprunts[] = $emprunt;
            $emprunt->setAbonne($this);
        }

        return $this;
    }

    public function removeEmprunt(Emprunt $emprunt): self
    {
        if ($this->emprunts->removeElement($emprunt)) {
            // set the owning side to null (unless already changed)
            if ($emprunt->getAbonne() === $this) {
                $emprunt->setAbonne(null);
            }
        }

        return $this;
    }
}

src/Entity/Emprunt.php
<?php

namespace App\Entity;

use App\Repository\EmpruntRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EmpruntRepository::class)
 */
class Emprunt
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_emprunt;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_retour;

    /**
     * @ORM\ManyToOne(targetEntity=Livre::class, inversedBy="emprunts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $livre;

    /**
     * @ORM\ManyToOne(targetEntity=Abonne::class, inversedBy="emprunts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $abonne;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateEmprunt(): ?\DateTimeInterface
    {
        return $this->date_emprunt;
    }

    public function setDateEmprunt(\DateTimeInterface $date_emprunt): self
    {
        $this->date_emprunt = $date_emprunt;

        return $this;
    }

    public function getDateRetour(): ?\DateTimeInterface
    {
        return $this->date_retour;
    }

    public function setDateRetour(?\DateTimeInterface $date_retour): self
    {
        $this->date_retour = $date_retour;

        return $this;
    }

    public function getLivre(): ?Livre
    {
        return $this->livre;
    }

    public function setLivre(?Livre $livre): self
    {
        $this->livre = $livre;

        return $this;
    }

    public function getAbonne(): ?Abonne
    {
        return $this->abonne;
    }

    public function setAbonne(?Abonne $abonne): self
    {
        $this->abonne = $abonne;

        return $this;
    }
}

src/Form/AbonneType.php
<?php

namespace App\Form;

use App\Entity\Abonne;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AbonneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $abonne=$options["data"];
        $builder
            ->add('pseudo')
            ->add('roles', ChoiceType::class, [
                "choices"=>[
                    "Lecteur"=>"ROLE_LECTEUR",
                    "Bibliothécaire"=>"ROLE_BIBLIO",
                    "Directeur"=>"ROLE_ADMIN",
                    "Abonné"=>"ROLE_USER",
                    "Développeur"=>"ROLE_DEV",
                ],
                "multiple"=> true,
                "expanded"=> true,
                "label"=> "Autorisations"
            ])
            ->add('password', TextType::class, [
                "required" => $abonne->getId() ? false : true,
                "mapped"=>false
            ])
            ->add('nom')
            ->add('prenom')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Abonne::class,
        ]);
    }
}

src/Controller/AbonneController.php
<?php

namespace App\Controller;

use App\Entity\Abonne;
use App\Form\AbonneType;
use App\Repository\AbonneRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Security\Http\Authenticator\Passport\UserPassportInterface;

#[Route('/admin/abonne')]
class AbonneController extends AbstractController
{
    #[Route('/', name: 'abonne_index', methods: ['GET'])]
    public function index(AbonneRepository $abonneRepository): Response
    {
        return $this->render('abonne/index.html.twig', [
            'abonnes' => $abonneRepository->findAll(),
        ]);
    }

    #[Route('/nouveau', name: 'abonne_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UserPasswordHasherInterface $hasher): Response
    {
        $abonne = new Abonne();
        $form = $this->createForm(AbonneType::class, $abonne);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $mdp = $form->get("password")->getData();
            $mdp = $hasher->hashPassword ($abonne, $mdp);
            $abonne->setPassword($mdp);
            $entityManager->persist($abonne);
            $entityManager->flush();

            return $this->redirectToRoute('abonne_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('abonne/new.html.twig', [
            'abonne' => $abonne,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'abonne_show', methods: ['GET'])]
    public function show(Abonne $abonne): Response
    {
        return $this->render('abonne/show.html.twig', [
            'abonne' => $abonne,
        ]);
    }

    #[Route('/{id}/edit', name: 'abonne_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, UserPasswordHasherInterface $hasher, Abonne $abonne): Response
    {
        $form = $this->createForm(AbonneType::class, $abonne);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $mdp = $form->get("password")->getData();
            if($mdp){
                $mdp = $hasher->hashPassword ($abonne, $mdp);
                $abonne->setPassword($mdp);
                }

            $this->getDoctrine()->getManager()->flush();
            $this->addFlash("success", "l'abonne a ete modifie");

            return $this->redirectToRoute('abonne_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('abonne/edit.html.twig', [
            'abonne' => $abonne,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'abonne_delete', methods: ['POST'])]
    public function delete(Request $request, Abonne $abonne): Response
    {
        if ($this->isCsrfTokenValid('delete'.$abonne->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($abonne);
            $entityManager->flush();
        }

        return $this->redirectToRoute('abonne_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/abonne/_delete_form.html.twig
<form method="post" action="{{ path('abonne_delete', {'id': abonne.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ abonne.id) }}">
    <button class="btn">Delete</button>
</form>

templates/abonne/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/abonne/edit.html.twig
{% extends 'admin/base.html.twig' %}

{% block title %}Edit Abonne{% endblock %}

{% block body %}
    <h1>Edit Abonne</h1>

    {{ include('abonne/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('abonne_index') }}">back to list</a>

    {{ include('abonne/_delete_form.html.twig') }}
{% endblock %}

templates/abonne/index.html.twig
{% extends 'admin/base.html.twig' %}

{% block title %}Liste des abonnée{% endblock %}

{% block body %}
    <h1>Abonne index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Pseudo</th>
                <th>Roles</th>
                <th>Password</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for abonne in abonnes %}
            <tr>
                <td>{{ abonne.id }}</td>
                <td>{{ abonne.pseudo }}</td>
                <td>{{ abonne.roles ? abonne.roles|json_encode : '' }}</td>
                <td>{{ abonne.password ? "***" : ""}}</td>
                <td>{{ abonne.nom }}</td>
                <td>{{ abonne.prenom }}</td>
                <td>
                    <a href="{{ path('abonne_show', {'id': abonne.id}) }}"><i class" fa fa-user"></i></a>
                    <a href="{{ path('abonne_edit', {'id': abonne.id}) }}"><i class"fa fa-edit"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">Aucun abonnée enregistré</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('abonne_new') }}" class"btn btn-primary">Ajouter</a>
{% endblock %}

templates/abonne/new.html.twig
{% extends 'admin/base.html.twig' %}

{% block title %}New Abonne{% endblock %}

{% block body %}
    <h1>Create new Abonne</h1>

    {{ include('abonne/_form.html.twig') }}

    <a href="{{ path('abonne_index') }}">back to list</a>
{% endblock %}

templates/abonne/show.html.twig
{% extends 'admin/base.html.twig' %}

{% block title %}Fiche abonné{% endblock %}

{% block body %}
    <h1>Fiche abonné</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ abonne.id }}</td>
            </tr>
            <tr>
                <th>Pseudo</th>
                <td>{{ abonne.pseudo }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ abonne.roles ? abonne.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ abonne.nom }}</td>
            </tr>
            <tr>
                <th>Prénom</th>
                <td>{{ abonne.prenom }}</td>
            </tr>

            <tr>
                <th>Emprunts</th>
                <td>
                    <table class="table">
                        <thead class="thead-dark">
                            <tr>
                                <th>Livre</th>
                                <th>Emprunté le</th>
                                <th>Rendu le</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for emprunt in abonne.emprunts %}
                            <tr>
                                <td>{{ emprunt.livre.titre ~ " - " ~ emprunt.livre.auteur }}</td>
                                <td>{{ emprunt.dateEmprunt|date('d/m/y') }}</td>
                                <td>{{ emprunt.dateRetour ? emprunt.dateRetour|date('d/m/y') : '' }}</td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="3">Aucun emprunt enregistré</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>                   
                </td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('abonne_index') }}">back to list</a>

    <a href="{{ path('abonne_edit', {'id': abonne.id}) }}">edit</a>

    {{ include('abonne/_delete_form.html.twig') }}
{% endblock %}